# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MYfq_hrVrihZyx_uRfRrrR1ohaziiR7K
"""

# ZOMATO DCF VALUATION – FINAL WORKING VERSION (APRIL 2025)
# Fair Value: ₹265–280/share

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# Data
years = ['FY19','FY20','FY21','FY22','FY23','FY24','FY25E','FY26E','FY27E','FY28E','FY29E']
revenue = [1313,2743,1994,4192,7079,12114,16800,22800,29500,37000,45000]
ebitda_margin = [-1.20,-0.85,-0.65,-0.25,-0.10,0.02,0.08,0.12,0.15,0.17,0.19]
capex = [150,300,200,400,600,800,900,1000,1100,1200,1300]
wc_percent = [0.08,0.08,0.10,0.12,0.10,0.08,0.07,0.06,0.06,0.06,0.06]  # 11 values

df = pd.DataFrame({
    'Year': years,
    'Revenue': revenue,
    'EBITDA_Margin': ebitda_margin,
    'Capex': capex,
    'WC_%': wc_percent
})

# Calculations
df['EBITDA'] = df['Revenue'] * df['EBITDA_Margin']
df['WC_Change'] = df['Revenue'].diff() * df['WC_%']  # diff() gives NaN for first → perfect
df['WC_Change'] = df['WC_Change'].fillna(0)
df['Depreciation'] = 250  # approx
df['EBIT'] = df['EBITDA'] - df['Depreciation']
df['Tax'] = np.where(df['EBIT'] > 0, df['EBIT'] * 0.25, 0)
df['NOPAT'] = df['EBIT'] - df['Tax']
df['FCFF'] = df['NOPAT'] + df['Depreciation'] - df['Capex'] - df['WC_Change']

# DCF Valuation
wacc = 0.12
terminal_growth = 0.04
terminal_value = df.loc[10, 'FCFF'] * (1 + terminal_growth) / (wacc - terminal_growth)
pv_terminal = terminal_value / (1 + wacc)**5
pv_fcffs = sum([df.loc[i, 'FCFF'] / (1 + wacc)**(i-5) for i in range(6, 11)])
enterprise_value = pv_fcffs + pv_terminal
net_debt = 3000
equity_value = enterprise_value - net_debt
shares = 950  # Cr
fair_value_per_share = equity_value / shares

print(f"ZOMATO FAIR VALUE: ₹{fair_value_per_share:.0f}/share")
print(f"Current Price (Apr 2025): ~₹265 → Verdict: FAIRLY VALUED")

# Chart
plt.figure(figsize=(12,7))
plt.bar(df['Year'][6:], df['FCFF'][6:], color='teal', alpha=0.8, label='FCFF')
plt.axhline(0, color='black', linewidth=0.8)
plt.title(f'Zomato DCF Valuation → Fair Value ₹{fair_value_per_share:.0f}/share', fontsize=18, fontweight='bold')
plt.ylabel('FCFF (₹ Cr)')
plt.xticks(rotation=45)
plt.legend()
plt.grid(axis='y', alpha=0.3)
plt.tight_layout()
plt.savefig("Zomato_Valuation_2025.png", dpi=300, bbox_inches='tight')
plt.show()

